### ISSUE TITLE
Right mode sliderpanel appears on left

### ISSUE THREAD

**Issue by desoca** [melistik/vaadin-sliderpanel#1]
Hello,

as request, when I run the following code the panel appears on the left of the browser instead of the right as it should.

It's basically the same example that was provided in the addon posting.

public class SliderPanelSampleUI extends UI {

```
@Override
protected void init(final VaadinRequest vaadinRequest) {
    final VerticalLayout mainLayout = new VerticalLayout();
    mainLayout.setSizeFull();
    mainLayout.setMargin(false);
    mainLayout.setSpacing(false);

    Label lbl = new Label("Hope this works!");
    SliderPanel rightSlider = new SliderPanel(lbl, SliderMode.RIGHT);
    rightSlider.setCaption("Right Slider");
    rightSlider.setTabPosition(SliderTabPosition.MIDDLE);

    mainLayout.addComponent(rightSlider);

    mainLayout.addComponent(new Label("Lots of Content ..."));
    setContent(mainLayout);
}
```

}

**Comment by melistik** [comment]
hi desoca,

I've just updated my documentation: https://github.com/melistik/vaadin-sliderpanel#layouting

Please take a look I hope the use is described better so that you can see that you need to place the slider to the right direction by yourself. 
As your example you need to change the addComponent order and then it should work.

Best regards
Marten
