### ISSUE TITLE
Rows of Grid on SliderPanel are rendered with height 1px

### ISSUE THREAD

**Issue by fwscholz** [melistik/vaadin-sliderpanel#5]
Adding a Grid with some rows to a SliderPanel and expanding it afterwards doesn't display any of them.
After some investigations I detected all rows are rendered with height 1px.
Are there any special things to consider using Grid on SliderPanel?
I'm using Vaadin 7.4.4 and current version of SliderPanel add-on.
Thanks in advance.

**Comment by melistik** [comment]
Hi, 
have you set a hight to the grid. The sliders trys to detect the height/width (depanding on which direction) and maybe there is a problem in combination with the grid. Could you please post your demo code? Otherwise it's hard for me to reproduce... Maybe the autodetection of Grid and SliderPanel have a problem in combination ;)

Thanks and best regards
Marten

**Comment by fwscholz** [comment]
Hello,
following the code:

``` java
@Theme("valo")
@Title("SliderPanelExample")
@Widgetset("fls.vaadin.widgetset.QAMWidgetSet")
public class SliderPanelExampleUI extends UI {

    @Override
    protected void init(VaadinRequest request) {
        setContent(initContent());
    }

    private HorizontalLayout initContent() {
        VerticalLayout middleContentLayout = new VerticalLayout();
        middleContentLayout.setSizeFull();
        middleContentLayout.setMargin(new MarginInfo(true, false, true, true));
        middleContentLayout.setSpacing(true);

        SliderPanel sliderPanelRight = initSliderPanel();

        HorizontalLayout horizontalLayout = new HorizontalLayout(middleContentLayout, sliderPanelRight);
        horizontalLayout.setSizeFull();
        horizontalLayout.setSpacing(true);

        horizontalLayout.setExpandRatio(middleContentLayout, 1f);

        return horizontalLayout;
    }

    private SliderPanel initSliderPanel() {
        VerticalLayout sliderPanelContent = initSliderPanelContent();

        SliderPanel sliderPanel = new SliderPanel(sliderPanelContent, SliderMode.RIGHT);
        sliderPanel.setCaption("Catalog");
        sliderPanel.setTabPosition(SliderTabPosition.MIDDLE);

        return sliderPanel;
    }

    private VerticalLayout initSliderPanelContent() {
        Grid grid = initGrid();

        HorizontalLayout innerLayout = new HorizontalLayout(grid);
        innerLayout.setSizeFull();
        innerLayout.setMargin(true);
        innerLayout.setSpacing(true);

        innerLayout.setExpandRatio(grid, 1f);

        Panel panel = new Panel(innerLayout);
        panel.setSizeFull();

        VerticalLayout layout = new VerticalLayout(panel);
        layout.setSizeFull();
        layout.setWidth(Page.getCurrent().getBrowserWindowWidth() * 0.7f, Unit.PIXELS);
        layout.setMargin(true);

        layout.setExpandRatio(panel, 1f);

        return layout;
    }

    private Grid initGrid() {
        Grid grid = new Grid("Products");
        grid.setSizeFull();

        grid.setSelectionMode(Grid.SelectionMode.MULTI);

        if (grid.getColumn("description") == null) {
            grid.addColumn("description", String.class);
        }
        if (grid.getColumn("price") == null) {
            grid.addColumn("price", BigDecimal.class).setRenderer(new NumberRenderer("%10.2f%n"));
        }

        for (int i = 1; i <= 50; i++) {
            grid.addRow("Product " + i, new BigDecimal(i));
        }

        grid.getColumn("description").setExpandRatio(3);
        grid.getColumn("price").setExpandRatio(2);

        grid.recalculateColumnWidths();

        return grid;
    }
}
```

Screenshot of the result:
![image](https://cloud.githubusercontent.com/assets/3685157/7224764/c021f812-e736-11e4-9983-d94993a3e019.png)

May you're right with Grid and SliderPanel have a problem in combination.
Many thanks for your investigation.

Regards,
Florian

**Comment by melistik** [comment]
Hi,
thank you for your demo and the code. I was able to reproduce your mention issue. But this is not a problem of the Slider iteself. When you set the Slider in the initial mode as expanded it works.

``` java
SliderPanel(sliderPanelContent, true, SliderMode.RIGHT);
```

It is painted as wished. Also in use of the Expand listener in initial collapsed mode (as your demo). I've tried some call on the grid to reinitialize it - but it still didn't worked:

``` java
sliderPanel.addListener(new SliderPanelListener() {
    @Override
    public void onToggle(final boolean expand) {
        if (expand) {
            grid.recalculateColumnWidths();
            grid.markAsDirty();
        }
    }
});
```

We should maybe create a ticket on vaadin itself for the grid. 

On the other hand you could maybe change your code so that the grid will only added when the slider is expanded the first time. When it has been painted in visible mode the display is correct and it works in combination with the slider... also after collapse and expand...

Sorry but I didn't fired any other proper solution :/

**Comment by melistik** [comment]
After a discussion with @mstahv I hope with the help of vaadin-team we could find a solution
