### ISSUE TITLE
Resize width/height of panel bar

### ISSUE THREAD

**Issue by cbelleza** [melistik/vaadin-sliderpanel#9]
If we try to resize via CSS the panel bar, it does no have effect. Even setting via Java code the width/height the bar keeps bigger that wanted. There's no way to get a new bar using full screen vertical dimensions, it always get the same default size.

**Comment by melistik** [comment]
please attach a code example for your problem that both width and height are not expaned 100% of the available screen within the layout. Further more your css hacking will not help because the size of the expanded content will get calculated and written directly as style to the div box - these cannot be overwritten by css outsite the div-element. 

What I can do is to allow to disable the auto detection of the sliders-content and allow to set it manually... Is this helping your with your problem?
